


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author bz433
 */
public class mainform extends javax.swing.JFrame {

   public static String mylist[];
 
   
    public mainform() {
        initComponents();
        mylist=D_read.readfile(); 
       D_sort sort_= new D_sort();
       mylist=sort_.sort();
//     for(int i =0;i<conter_tool();i++){
//          String [] result = mainform.mylist[i].split(",");
//        jedit.j_code.setText(result[3]);
//          jedit.jnew_name.setText(result[0]);
//          jnew_manufactor.setSelectedItem(result[1]);
//          jnew_number.setText(result[4]);
//          jnew_price.setText(result[2]);
//     }
Edit_data rr= new Edit_data(mylist);
       tabledata table = new tabledata();
        
    }
    public static int conter_tool(){
        int conter=0;
        for (int i =0;i<mainform.mylist.length;i++){
            if (mylist[i]==null){
                break;
            }
            if (mylist[i]!=null){
                conter++;
            }
        }
        return conter;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jdatatable = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        add_group = new javax.swing.JMenu();
        jadd_tools = new javax.swing.JMenuItem();
        search = new javax.swing.JMenu();
        jsearch = new javax.swing.JMenuItem();
        help = new javax.swing.JMenu();
        jhelp = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jdatatable.setBackground(new java.awt.Color(153, 255, 0));
        jdatatable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jdatatable.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jdatatableAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jScrollPane1.setViewportView(jdatatable);

        add_group.setText("File");

        jadd_tools.setText("add_tools");
        jadd_tools.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jadd_toolsActionPerformed(evt);
            }
        });
        add_group.add(jadd_tools);

        jMenuBar1.add(add_group);

        search.setText("search");

        jsearch.setText("search");
        jsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jsearchActionPerformed(evt);
            }
        });
        search.add(jsearch);

        jMenuBar1.add(search);

        help.setText("Help");

        jhelp.setText("help");
        jhelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jhelpActionPerformed(evt);
            }
        });
        help.add(jhelp);

        jMenuBar1.add(help);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1044, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 737, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jhelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jhelpActionPerformed
             jhelp help = new jhelp();
             help.setVisible(true);
    }//GEN-LAST:event_jhelpActionPerformed

    private void jadd_toolsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jadd_toolsActionPerformed
        jadd_tools add = new jadd_tools();
        add.setVisible(true);
    }//GEN-LAST:event_jadd_toolsActionPerformed

    private void jsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jsearchActionPerformed
     jsearch search = new jsearch();
     search.setVisible(true);
    }//GEN-LAST:event_jsearchActionPerformed

    private void jdatatableAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jdatatableAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jdatatableAncestorAdded

    /**
     * @param args the command line ar


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author bz433
 */
public class mainform extends javax.swing.JFrame {

   public static String mylist[];
 
   
    public mainform() {
        initComponents();
        mylist=D_read.readfile(); 
       D_sort sort_= new D_sort();
       mylist=sort_.sort();
//     for(int i =0;i<conter_tool();i++){
//          String [] result = mainform.mylist[i].split(",");
//        jedit.j_code.setText(result[3]);
//          jedit.jnew_name.setText(result[0]);
//          jnew_manufactor.setSelectedItem(result[1]);
//          jnew_number.setText(result[4]);
//          jnew_price.setText(result[2]);
//     }
Edit_data rr= new Edit_data(mylist);
       tabledata table = new tabledata();
        
    }
    public static int conter_tool(){
        int conter=0;
        for (int i =0;i<mainform.mylist.length;i++){
            if (mylist[i]==null){
                break;
            }
            if (mylist[i]!=null){
                conter++;
            }
        }
        return conter;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jdatatable = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        add_group = new javax.swing.JMenu();
        jadd_tools = new javax.swing.JMenuItem();
        search = new javax.swing.JMenu();
        jsearch = new javax.swing.JMenuItem();
        help = new javax.swing.JMenu();
        jhelp = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jdatatable.setBackground(new java.awt.Color(153, 255, 0));
        jdatatable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jdatatable.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jdatatableAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jScrollPane1.setViewportView(jdatatable);

        add_group.setText("File");

        jadd_tools.setText("add_tools");
        jadd_tools.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jadd_toolsActionPerformed(evt);
            }
        });
        add_group.add(jadd_tools);

        jMenuBar1.add(add_group);

        search.setText("search");

        jsearch.setText("search");
        jsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jsearchActionPerformed(evt);
            }
        });
        search.add(jsearch);

        jMenuBar1.add(search);

        help.setText("Help");

        jhelp.setText("help");
        jhelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jhelpActionPerformed(evt);
            }
        });
        help.add(jhelp);

        jMenuBar1.add(help);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1044, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 737, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jhelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jhelpActionPerformed
             jhelp help = new jhelp();
             help.setVisible(true);
    }//GEN-LAST:event_jhelpActionPerformed

    private void jadd_toolsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jadd_toolsActionPerformed
        jadd_tools add = new jadd_tools();
        add.setVisible(true);
    }//GEN-LAST:event_jadd_toolsActionPerformed

    private void jsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jsearchActionPerformed
     jsearch search = new jsearch();
     search.setVisible(true);
    }//GEN-LAST:event_jsearchActionPerformed

    private void jdatatableAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jdatatableAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jdatatableAncestorAdded

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainform().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu add_group;
    private javax.swing.JMenu help;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenuItem jadd_tools;
    public static javax.swing.JTable jdatatable;
    private javax.swing.JMenuItem jhelp;
    private javax.swing.JMenuItem jsearch;
    private javax.swing.JMenu search;
    // End of variables declaration//GEN-END:variables
}
